DATA:
  BATCH_SIZE: 32
  DATASET: imagenet
  DATA_PATH: /data/dataset/ImageNet/extract
  IMG_SIZE: 384
  INTERPOLATION: bicubic
  ZIP_MODE: False
  CACHE_MODE: "part"
  PIN_MEMORY: True
  NUM_WORKERS: 8

MODEL:
  PRETRAINED: True
  RESUME: ""
  LABEL_SMOOTHING: 0.1

TRAIN:
  START_EPOCH: 0
  EPOCHS: 90
  WARMUP_EPOCHS: 0
  WEIGHT_DECAY: 1e-4
  BASE_LR: 0.1
  WARMUP_LR: 5e-7
  CLIP_GRAD: 5.0
  AUTO_RESUME: False
  ACCUMULATION_STEPS: 0
  
  LR_SCHEDULER:
    NAME: step

  OPTIMIZER:
    NAME: sgd
    MOMENTUM: 0.9
  
AUG:
  COLOR_JITTER: 0.4
  AUTO_AUGMENT: rand-m9-mstd0.5-inc1
  REPROB: 0.25
  MIXUP: 0.0
  CUTMIX: 0.0
  CUTMIX_MINMAX: None

TEST:
  CROP: True
  SEQUENTIAL: False

TAG: default
SAVE_FREQ: 1
PRINT_FREQ: 50
SEED: 42
EVAL_MODE: True
THROUGHPUT_MODE: False